Repository Binnarium/mobile-2222, pull requests merged in 2021-08, with the labels that each got.

#105 Fix/dias_restantes
  lib/screens/profile.screen.dart
  lib/screens/splash.screen.dart
  lib/shared/widgets/days_left_widget.dart
Labels: bug

#123 Feature/diseño-chat
  lib/chat/screens/chat.screen.dart
  lib/themes/colors.dart
Labels: enhancement

#125 Feature/list-chats-desing
  lib/chat/screens/list-chats.screen.dart
  lib/shared/widgets/chapter-head-banner_widget.dart
  lib/shared/widgets/custom_navigation_bar.dart
Labels: duplicate

#148 Feature/colaboraciones
  lib/cities/activity/widgets/activities.screen.dart
  lib/models/city.dto.dart
  lib/models/player-contributions.dto.dart
  lib/screens/chapter_screens/city-contribution.screen.dart
  lib/screens/chapter_screens/contribution-ideas.screen.dart
  lib/services/load-player-information.service.dart
  lib/services/upload-contribution.service.dart
  lib/shared/routes/routes.dart
  lib/shared/widgets/markdown.widget.dart
  lib/widgets/scaffold-2222/scaffold-2222.widget.dart
Labels: bug, enhancement

#154 Micro-meso-macro screen
  lib/models/city.dto.dart
  lib/models/micro-meso-macro.dto.dart
  lib/screens/chapter_screens/micro_meso_macro.screen..dart
  lib/services/load-micro-meso-macro.service.dart
  lib/shared/routes/routes.dart
  lib/widgets/scaffold-2222/scaffold-2222.widget.dart
Labels: enhancement
