Repository Binnarium/mobile-2222, pull requests merged in 2021-10, with the labels that each got.

#260 Delete messages, days left, never sleep videos
  lib/app-provider.dart
  lib/assets/video/services/current-video.provider.dart
  lib/chat/models/message.model.dart
  lib/chat/services/delete-message.service.dart
  lib/chat/ui/screens/detailed-video.screen.dart
  lib/chat/ui/widgets/message-list.widget.dart
  lib/chat/ui/widgets/message.widget.dart
  lib/cities/contribution/ui/screens/contribution-explanation.screen.dart
  lib/cities/contribution/ui/widget/contribution-code-copy.dart
  lib/shared/widgets/days_left_widget.dart
  lib/shared/widgets/project-gallery.widget.dart
  lib/user/widgets/widgets/listSocialNetworks.widget.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement

#264 Feature/gamiffication audio
  lib/player/ui/screens/profile.screen.dart
  lib/player/ui/widgets/player-gammification.widget.dart
  lib/points-explanation/uid/widgets/points-explanation.widget.dart
Labels: bug

#263 Added gameover and nextphase pages, control flags to player model
  lib/app-routing.dart
  lib/chat/ui/widgets/message.widget.dart
  lib/cities/monster/ui/screens/stageMonster.screen.dart
  lib/city/models/city-enabled-pages.model.dart
  lib/city/ui/screen/home.screen.dart
  lib/player/models/player.model.dart
  lib/player/services/get-current-player.service.dart
  lib/thanks-videos/widgets/game-over.screen.dart
  lib/thanks-videos/widgets/next-phase-video.screen.dart
  lib/widgets/scaffold-2222/services/cities-navigation.service.dart
Labels: enhancement

#270 feature/Scoreboard
  lib/app-provider.dart
  lib/app-routing.dart
  lib/player/models/player.model.dart
  lib/player/ui/screens/profile.screen.dart
  lib/player/ui/screens/scoreboard.screen.dart
  lib/services/load-players-scoreboard.service.dart
  lib/user/widgets/widgets/list-scoreboard.widget.dart
  lib/widgets/scaffold-2222/services/cities-navigation.service.dart
Labels: enhancement
