Repository Binnarium/mobile-2222, pull requests merged in 2021-09, with the labels that each got.

#158 projects stream
  lib/screens/chapter_screens/city-project.screen.dart
  lib/services/load-player-information.service.dart
Labels: enhancement

#169 Feature/fix project screen
  assets/images/empty-projects.png
  lib/cities/activity/widgets/activities.screen.dart
  lib/cities/clubhouse/ui/screens/clubhouse.screen.dart
  lib/models/player-projects.dto.dart
  lib/screens/chapter_screens/city-project.screen.dart
  lib/screens/chapter_screens/micro_meso_macro.screen..dart
  lib/services/load-player-information.service.dart
  lib/services/upload-file.service.dart
  lib/shared/widgets/project-gallery.widget.dart
  lib/shared/widgets/upload-file-dialog.widget.dart
Labels: enhancement

#176 Changed avatar image logic
  lib/player/ui/screens/profile.screen.dart
  lib/screens/chapter_screens/content.screen.dart
  lib/screens/welcome.screen.dart
  lib/services/load-player-information.service.dart
  lib/shared/widgets/videoPlayer_widget.dart
  lib/user/widgets/login.screen.dart
Labels: bug, enhancement

#179 Feature/contribuciones screen
  lib/cities/activity/widgets/activities.screen.dart
  lib/models/player-contributions.dto.dart
  lib/screens/chapter_screens/city-contribution.screen.dart
  lib/screens/chapter_screens/contribution-ideas.screen.dart
  lib/screens/chapter_screens/contribution.screen.dart
  lib/services/load-city-history.service.dart
  lib/services/load-contributions-screen.dart
  lib/services/load-player-information.service.dart
  lib/services/upload-contribution.service.dart
  lib/shared/routes/routes.dart
  lib/widgets/scaffold-2222/scaffold-2222.widget.dart
Labels: bug, enhancement

#180 Feature/introductory video
  assets/icons/city_icon.png
  assets/icons/coin_icon.png
  assets/icons/upload_project_2_icon.png
  assets/icons/upload_project_icon.png
  assets/images/empty-projects.png
  lib/screens/chapter_screens/introductory-video.screen.dart
  lib/shared/widgets/project-gallery.widget.dart
  lib/widgets/scaffold-2222/scaffold-2222.widget.dart
Labels: enhancement

#181 Fix/contributionText
  lib/screens/chapter_screens/city-contribution.screen.dart
  lib/screens/chapter_screens/contribution-ideas.screen.dart
Labels: bug

#182 multimedia chats
  lib/chat/services/send-message.service.dart
  lib/chat/ui/screens/detailed-multimedia.screen.dart
  lib/chat/ui/widgets/message.widget.dart
  lib/chat/ui/widgets/messages-input.dart
  lib/chat/ui/widgets/uploadMultimediaDialog.widget.dart
  lib/player/ui/screens/profile.screen.dart
  lib/providers/videoPlayer_provider.dart
  lib/screens/chapter_screens/city-project.screen.dart
  lib/services/upload-file.service.dart
  lib/shared/widgets/upload-file-dialog.widget.dart
  lib/shared/widgets/videoPlayer_widget.dart
Labels: enhancement

#194 fix/textProject
  lib/screens/chapter_screens/city-project.screen.dart
  lib/shared/widgets/project-gallery.widget.dart
Labels: bug

#195 feature/explanationClubHouse
  lib/app-routes.dart
  lib/cities/clubhouse/ui/screens/clubhouse-explanation.screen.dart
  lib/cities/clubhouse/ui/screens/clubhouse.screen.dart
  lib/widgets/scaffold-2222/scaffold-2222.widget.dart
  lib/widgets/scaffold-2222/services/cities-navigation.service.dart
Labels: bug, enhancement

#196 Feature/video messages
  lib/app-222.dart
  lib/assets/video/services/upload-video.service.dart
  lib/chat/ui/widgets/messages-input.dart
  lib/models/asset.dto.dart
Labels: enhancement

#197 Refactorización de pantalla de proyecto
  lib/app-222.dart
  lib/cities/project/models/player-projects.model.dart
  lib/cities/project/services/upload-file.service.dart
  lib/cities/project/services/upload-project.service.dart
  lib/models/asset.dto.dart
  lib/player/services/update-avatar.service.dart
  lib/player/ui/screens/profile.screen.dart
  lib/screens/chapter_screens/city-project.screen.dart
  lib/services/load-player-information.service.dart
  lib/services/upload-file.service.dart
  lib/shared/widgets/project-gallery.widget.dart
  lib/shared/widgets/upload-file-dialog.widget.dart
Labels: documentation, enhancement

#202 Profile screen design
  assets/gamification/2222_medalla-clubhouse.png
  assets/gamification/2222_monedas.png
  assets/gamification/2222_proactivo_amarillo.png
  assets/gamification/2222_proactivo_rojo.png
  assets/gamification/2222_proactivo_verde.png
  lib/player/ui/screens/profile.screen.dart
  lib/player/widgets/user-gamification.widget.dart
  pubspec.yaml
Labels: enhancement

#205 Fix/tamañoTextos
  lib/cities/clubhouse/ui/screens/clubhouse.screen.dart
  lib/cities/contribution/ui/screens/contribution-explanation.screen.dart
  lib/screens/chapter_screens/city-project.screen.dart
Labels: bug

#208 Structured profile screen
  lib/player/models/coinsImages.model.dart
  lib/player/ui/screens/profile.screen.dart
  lib/player/widgets/changeAvatarButton.widget.dart
  lib/player/widgets/gamification-item.widget.dart
  lib/player/widgets/gammification-number.widget.dart
  lib/player/widgets/player-gammification.widget.dart
Labels: documentation

#212 Refactorization of services
  lib/app-222.dart
  lib/app-routes.dart
  lib/cities/activity/services/load-activity.service.dart
  lib/cities/activity/widgets/activities.screen.dart
  lib/cities/clubhouse/services/load-clubhouse-activity.service.dart
  lib/cities/clubhouse/ui/screens/clubhouse.screen.dart
  lib/cities/final-video/services/load-final-video.service.dart
  lib/cities/final-video/widgets/final-video.screen.dart
  lib/cities/manual-video/services/load-manual-video.service.dart
  lib/cities/manual-video/widgets/manual-video.screen.dart
  lib/cities/micro-meso-macro/services/load-micro-meso-macro.service.dart
  lib/cities/micro-meso-macro/ui/screens/micro-meso-macro.screen.dart
  lib/cities/micro-meso-macro/ui/widgets/micro-meso-macro-description-text.widget.dart
  lib/cities/project-video/services/load-project-video.service.dart
  lib/cities/project-video/widgets/project-video.screen.dart
  lib/cities/project/services/upload-file.service.dart
  lib/cities/project/services/upload-project.service.dart
  lib/models/content-dto.dto.dart
  lib/player/services/update-avatar.service.dart
  lib/screens/chapter_screens/city-introduction.screen.dart
  lib/screens/chapter_screens/city-project.screen.dart
  lib/screens/chapter_screens/introductory-video.screen.dart
  lib/screens/chapter_screens/resources.screen.dart
  lib/screens/chapter_screens/stageHistory.screen.dart
  lib/screens/welcome.screen.dart
  lib/services/load-city-history.service.dart
  lib/services/load-city-introduction.service.dart
  lib/services/load-city-introductory-video.service.dart
  lib/services/load-city-resources.service.dart
  lib/services/load-login-information.service.dart
  lib/services/load-project-activity.service.dart
  lib/start-video/services/load-start-video.service.dart
  lib/start-video/widgets/start-video.screen.dart
  lib/team/services/load-team.service.dart
  lib/team/ui/screens/team.screen.dart
  lib/user/widgets/login.screen.dart
  lib/widgets/scaffold-2222/services/cities-navigation.service.dart
Labels: documentation

#224 Refactorizing LoadContentsScreenInformationService & LoadArgumentScreenInformationService services
  lib/app-222.dart
  lib/screens/chapter_screens/content.screen.dart
  lib/screens/chapter_screens/stageArgumentation.screen.dart
  lib/services/load-arguments-screen-information.service.dart
  lib/services/load-contents-screen-information.service.dart
Labels: documentation, duplicate

#223 Feature/minor design fixes
  lib/app-222.dart
  lib/player/ui/screens/profile.screen.dart
  lib/player/ui/widgets/gamification-item.widget.dart
  lib/player/ui/widgets/gammification-number.widget.dart
  lib/player/ui/widgets/player-gammification.widget.dart
  lib/points-explanation/services/get-points-explanation.service.dart
  lib/points-explanation/uid/widgets/points-explanation.widget.dart
  lib/screens/chapter_screens/stageobjectives.screen.dart
  lib/team/ui/widgets/goto-team-button.widget.dart
Labels: documentation, enhancement

#226 feature/list-players-maraton
  lib/app-routes.dart
  lib/player/models/player.model.dart
  lib/player/services/list-player-group.service.dart
  lib/player/ui/widgets/participants-list-medals.widget.dart
  lib/screens/chapter_screens/city-medals-hackaton.screen.dart
  lib/widgets/scaffold-2222/services/cities-navigation.service.dart
Labels: bug, enhancement

#232 fixed the problem of uploading the project.
  lib/app-provider.dart
  lib/cities/project/models/player-projects.model.dart
  lib/cities/project/services/load-project-files.service.dart
  lib/cities/project/services/upload-file.service.dart
  lib/cities/project/services/upload-project.service.dart
  lib/cities/project/ui/screens/project.screen.dart
  lib/models/project.model.dart
Labels: bug

#233 lint refactorization
  lib/assets/audio/model/audio-player.extension.dart
  lib/assets/audio/model/audio-position.model.dart
  lib/assets/audio/services/current-audio.provider.dart
  lib/assets/audio/ui/audio-controls.widget.dart
  lib/assets/audio/ui/audio-player.widget.dart
  lib/assets/audio/ui/audio-slider.widget.dart
  lib/assets/image/services/upload-image.service.dart
  lib/assets/video/services/current-video.provider.dart
  lib/assets/video/services/upload-video.service.dart
  lib/assets/video/ui/widgets/video-player.widget.dart
  lib/chat/models/chat-participant.model.dart
  lib/chat/models/chat.model.dart
  lib/chat/models/create-personal-chat-query.model.dart
  lib/chat/models/create-personal-chat-response.model.dart
  lib/chat/models/message.model.dart
  lib/chat/models/search-chat-query.model copy.dart
  lib/chat/models/search-chat-response.model.dart
  lib/chat/services/create-personal-chats.service.dart
  lib/chat/services/get-chat.service.dart
  lib/chat/services/list-messages.service.dart
  lib/chat/services/list-player-chats.service.dart
  lib/chat/services/send-message.service.dart
  lib/chat/ui/screens/chat-participants.screen.dart
  lib/chat/ui/screens/chats.screen.dart
  lib/chat/ui/screens/detailed-multimedia.screen.dart
  lib/chat/ui/screens/messages.screen.dart
  lib/chat/ui/widgets/chat-list-item.widget.dart
  lib/chat/ui/widgets/chat-text-description.widget.dart
  lib/chat/ui/widgets/message-list.widget.dart
  lib/chat/ui/widgets/message.widget.dart
  lib/chat/ui/widgets/messages-input.dart
  lib/chat/ui/widgets/participants-list-item.widget.dart
  lib/chat/ui/widgets/participants-list-title.widget.dart
  lib/cities/activity/model/city-activity.model.dart
  lib/cities/activity/services/load-activity.service.dart
  lib/cities/activity/widgets/activities.screen.dart
  lib/cities/argument-ideas/ui/widget/idea-bubble.widget.dart
  lib/cities/clubhouse/models/clubhouse-activity.model.dart
  lib/cities/clubhouse/models/clubhouse-explanation.model.dart
  lib/cities/clubhouse/models/clubhouse.model.dart
  lib/cities/clubhouse/models/create-clubhouse.model.dart
  lib/cities/clubhouse/services/get-clubhouse-explanation.service.dart
  lib/cities/clubhouse/services/load-available-clubhouse.service.dart
  lib/cities/clubhouse/services/load-clubhouse-activity.service.dart
  lib/cities/clubhouse/services/load-user-clubhouse.service.dart
  lib/cities/contribution/models/collaborations.model.dart
  lib/cities/contribution/models/contribution-explanation.model.dart
  lib/cities/contribution/services/get-clubhouse-explanation.service.dart
  lib/cities/contribution/services/get-collaboration-explanation.service.dart
  lib/cities/contribution/ui/screens/city-contribution.screen.dart
  lib/cities/contribution/ui/screens/contribution-explanation.screen.dart
  pubspec.lock
Labels: documentation

#236 Video player now shows on different screen
  lib/assets/video/ui/widgets/video-player.widget.dart
  lib/chat/ui/screens/detailed-multimedia.screen.dart
  lib/chat/ui/widgets/message.widget.dart
  lib/screens/chapter_screens/content.screen.dart
  lib/shared/widgets/videoPlaceholder.widget.dart
Labels: enhancement

#240 Fix of podcast audio
  lib/app-routing.dart
  lib/assets/audio/ui/audio-player.widget.dart
  lib/cities/clubhouse/services/clubhouse.service.dart
  lib/widgets/scaffold-2222/scaffold-2222.widget.dart
  pubspec.lock
Labels: bug

#239 Feature/maratonMedals
  lib/app-provider.dart
  lib/cities/project/models/player-maraton-medal.model.dart
  lib/cities/project/services/upload-maraton-medal.service.dart
  lib/player/models/player.model.dart
  lib/player/ui/widgets/participants-list-medals.widget.dart
  lib/player/ui/widgets/player-gammification.widget.dart
  lib/project-awards/ui/screens/project-awards.screen.dart
Labels: bug, enhancement

#242 Check appears if user owns a medal on project screen
  lib/cities/project/models/player-maraton-medal.model.dart
  lib/cities/project/services/upload-maraton-medal.service.dart
  lib/cities/project/ui/screens/project.screen.dart
  lib/cities/project/ui/widgets/coins_check.widget.dart
Labels: enhancement

#243 feature/medalawarded
  lib/cities/clubhouse/services/clubhouse.service.dart
  lib/cities/project/services/upload-maraton-medal.service.dart
  lib/player/ui/widgets/participants-list-medals.widget.dart
  lib/project-awards/ui/screens/project-awards.screen.dart
  pubspec.lock
Labels: bug, enhancement

#246 Added title to the city 0 videos, and added the coin check to contribution and clubhouse screens.
  lib/cities/clubhouse/ui/screens/clubhouse.screen.dart
  lib/cities/contribution/ui/screens/city-contribution.screen.dart
  lib/screens/chapter_screens/content.screen.dart
  lib/screens/welcome.screen.dart
  lib/shared/widgets/content-title.widget.dart
  lib/user/widgets/login.screen.dart
Labels: enhancement

#248 feature/socialNetworks
  lib/screens/welcome.screen.dart
  lib/user/widgets/login.screen.dart
  lib/user/widgets/widgets/listSocialNetworks.widget.dart
Labels: enhancement
